# Generated by Django 6.0.6 on 2026-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_contact_email_event_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_flagship',
            field=models.BooleanField(default=False),
        ),
    ]
