# Generated by Django 6.0.6 on 2026-07-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_flagship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_flagship',
        ),
    ]
