# Generated by Django 6.0.6 on 2026-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_is_flagship'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_flagship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
