# Generated by Django 6.0.6 on 2026-07-13 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_flagship'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Past Event',
                'verbose_name_plural': 'Past Events',
                'db_table': 'events_pastevent',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
