# Generated by Django 6.0.6 on 2026-07-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_pastevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='faqs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
