# Generated by Django 6.0.6 on 2026-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='If True, registrations require admin approval. If False, they are automatically Approved (unless capacity is full).'),
        ),
    ]
