# Generated by Django 6.0.6 on 2026-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_requires_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_checkin_active',
            field=models.BooleanField(default=False, help_text='If True, volunteers can check in users. Admins can always check in.'),
        ),
    ]
