# Generated by Django 6.0.6 on 2026-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_is_checkin_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.PositiveIntegerField(default=0, help_text='Registration fee in INR. 0 means free.'),
        ),
    ]
