# Generated by Django 6.0.6 on 2026-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_continuous',
            field=models.BooleanField(default=True, help_text='If checked, check-in is required only once. If unchecked, check-in is required on each individual day.'),
        ),
    ]
