# Generated by Django 6.0.6 on 2026-07-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_is_continuous'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_registration_url',
            field=models.URLField(blank=True, help_text='Redirect URL if registration is hosted externally.', max_length=500, null=True),
        ),
    ]
