# Generated by Django 6.0.6 on 2026-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_external_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
