# Generated by Django 6.0.6 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_external_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_fee_per_team',
            field=models.BooleanField(default=False, help_text='If True, the registration fee applies per team instead of per person.'),
        ),
    ]
