# Generated by Django 6.0.6 on 2026-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_judges_event_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee_type',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_team', 'Per Team')], default='per_person', help_text='Whether the fee is per person or per team.', max_length=20),
        ),
    ]
