# Generated by Django 6.0.6 on 2026-06-23 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'registrations_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('qr_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('qr_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('waitlist_position', models.IntegerField(blank=True, null=True)),
                ('is_team_registration', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='registrations.team')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registrations.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'registrations_teammember',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['event'], name='registratio_event_i_ea7973_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['leader'], name='registratio_leader__b856a3_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='registratio_status_ca19f3_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event'], name='registratio_event_i_c30af8_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user'], name='registratio_user_id_22bc2d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_42419d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['qr_token'], name='registratio_qr_toke_5bd333_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['waitlist_position'], name='registratio_waitlis_c75c96_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_registration'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='registratio_team_id_438146_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['confirmation_token'], name='registratio_confirm_8babdb_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='registratio_email_d39074_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'email'), name='unique_team_email'),
        ),
    ]
