"""
Users app services.

All business logic for authentication and user management lives here.
Views call these functions — never put logic in views or serializers.

Functions:
- send_magic_link(email)        → creates/gets user, sends magic link email
- verify_magic_link(token)      → validates sesame token, returns user
- update_user_profile(user, data) → updates mutable profile fields
- change_user_role(user, role)  → changes a user's role (admin only action)

CU domain detection:
- @cuchd.in and @cumail.in → is_cu_student = True
- Everything else          → is_cu_student = False
"""

import logging
from uuid import UUID

from django.conf import settings

from core.exceptions import AppError
from core.utils.email import send_magic_link_email
from users.models import User, UserRole

logger = logging.getLogger(__name__)

# CU email domains as specified in AGENT_CONTEXT.md and ARCHITECTURE.md
CU_DOMAINS = {'cuchd.in', 'cumail.in'}


def _is_cu_student(email: str) -> bool:
    """Derive CU student status from email domain."""
    try:
        domain = email.split('@')[1].lower()
        return domain in CU_DOMAINS
    except IndexError:
        return False


def send_magic_link(email: str) -> None:
    """
    Send a magic link login email to the given address.

    - Creates a new user if the email is not in the system yet.
    - New users are always created with role='student'.
    - is_cu_student is derived from the email domain.
    - The magic link token is generated by django-sesame.
    - The email is sent via Azure Communication Services.

    This function does NOT reveal whether the email already exists
    (per API_SPEC.md security note).

    Raises:
        AppError: If token generation or email sending fails critically.
    """
    from sesame.utils import get_token

    email = email.strip().lower()

    # Get or create the user — new users get student role by default
    user, created = User.objects.get_or_create(
        email=email,
        defaults={
            'full_name': '',  # Will be filled at first registration
            'is_cu_student': _is_cu_student(email),
            'role': UserRole.STUDENT,
        }
    )

    if created:
        logger.info('New user created via magic link request: %s', email)

    # Generate sesame token — signed, time-limited (SESAME_MAX_AGE = 900s)
    token = get_token(user)

    # Build the verification URL pointing to the backend API
    # Frontend reads the token from its own /login?token= route and hits this endpoint
    verify_url = f'{settings.FRONTEND_URL}/auth/verify?token={token}'

    # Send the email — stubs if Azure not configured locally
    send_magic_link_email(to=email, magic_link_url=verify_url)


def verify_magic_link(token: str, request) -> User:
    """
    Verify a magic link token and return the authenticated user.

    - Uses django-sesame's authenticate() to validate the token.
    - The token is single-use and expires after SESAME_MAX_AGE seconds.
    - On success, Django session is established by the calling view.

    Args:
        token: The sesame token from the query string.
        request: The Django request object (required by sesame).

    Returns:
        The authenticated User instance.

    Raises:
        AppError(INVALID_TOKEN, 400): If the token is invalid or expired.
    """
    from sesame.utils import get_user

    user = get_user(token)

    if user is None:
        raise AppError(
            code='INVALID_TOKEN',
            message='This link is invalid or has expired. Please request a new one.',
            status=400,
        )

    # Sync is_staff with role — admin users need is_staff=True for Django Admin
    if user.role == UserRole.ADMIN and not user.is_staff:
        User.objects.filter(pk=user.pk).update(is_staff=True)
        user.is_staff = True

    logger.info('User logged in via magic link: %s', user.email)
    return user


def update_user_profile(user: User, validated_data: dict) -> User:
    """
    Update mutable profile fields on the user's own account.

    Only updates fields provided in validated_data (PATCH semantics).
    Email and role cannot be changed here.

    Returns the updated user instance.
    """
    for field, value in validated_data.items():
        setattr(user, field, value)
    user.save(update_fields=list(validated_data.keys()) + ['updated_at'])
    return user


def change_user_role(target_user: User, new_role: str, changed_by: User) -> User:
    """
    Change a user's role. Admin-only action — enforced by view permissions.

    Syncs is_staff when changing to/from admin role.

    Args:
        target_user: The user whose role is being changed.
        new_role: One of 'student', 'volunteer', 'admin'.
        changed_by: The admin performing the change (for audit logging).

    Returns the updated user instance.
    """
    if new_role not in UserRole.values:
        raise AppError(
            code='VALIDATION_ERROR',
            message='Invalid role.',
            fields={'role': f'Must be one of: {", ".join(UserRole.values)}.'},
            status=400,
        )

    old_role = target_user.role
    target_user.role = new_role

    # Keep is_staff in sync with admin role
    target_user.is_staff = (new_role == UserRole.ADMIN)
    target_user.is_superuser = (new_role == UserRole.ADMIN)

    target_user.save(update_fields=['role', 'is_staff', 'is_superuser', 'updated_at'])

    logger.info(
        'User %s role changed from %s to %s by admin %s',
        target_user.email, old_role, new_role, changed_by.email,
    )
    return target_user


def get_user_list(role: str | None = None, search: str | None = None):
    """
    Return a queryset of all users, optionally filtered.
    Admin-only — permission enforced by view.
    """
    qs = User.objects.all()

    if role:
        if role not in UserRole.values:
            raise AppError(
                code='VALIDATION_ERROR',
                message='Invalid role filter.',
                fields={'role': f'Must be one of: {", ".join(UserRole.values)}.'},
            )
        qs = qs.filter(role=role)

    if search:
        from django.db.models import Q
        qs = qs.filter(
            Q(full_name__icontains=search) | Q(email__icontains=search)
        )

    return qs
