"""
Users app services.

All business logic for authentication and user management lives here.
Views call these functions — never put logic in views or serializers.

Functions:
- send_magic_link(email)        → creates/gets user, sends magic link email
- verify_magic_link(token)      → validates sesame token, returns user
- update_user_profile(user, data) → updates mutable profile fields
- change_user_role(user, role)  → changes a user's role (admin only action)

CU domain detection:
- @cuchd.in and @cumail.in → is_cu_student = True
- Everything else          → is_cu_student = False
"""

import logging
from uuid import UUID

from django.conf import settings

from core.exceptions import AppError
from core.utils.email import send_magic_link_email
from users.models import User, UserRole

logger = logging.getLogger(__name__)

# CU email domains as specified in AGENT_CONTEXT.md and ARCHITECTURE.md
CU_DOMAINS = {'cuchd.in', 'cumail.in'}


def _is_cu_student(email: str) -> bool:
    """Derive CU student status from email domain."""
    try:
        domain = email.split('@')[1].lower()
        return domain in CU_DOMAINS
    except IndexError:
        return False


def send_magic_link(email: str) -> None:
    """
    Send a magic link login email to the given address.

    - The magic link token is generated by django TimestampSigner.
    - The email is sent via Azure Communication Services.
    - Rate limited to 3 requests per 15 minutes per email.

    This function does NOT reveal whether the email already exists
    (per API_SPEC.md security note).

    Raises:
        AppError: If rate limit exceeded or email sending fails critically.
    """
    from django.core.signing import TimestampSigner
    from django.core.cache import cache

    email = email.strip().lower()

    # Rate limiting: max 3 requests per 15 minutes
    cache_key = f'magic_link_req_{email}'
    cache.add(cache_key, 0, timeout=900)
    req_count = cache.incr(cache_key)
    if req_count > 3:
        raise AppError(
            code='RATE_LIMIT_EXCEEDED',
            message='Too many requests. Please try again later.',
            status=429
        )


    from urllib.parse import urlencode

    signer = TimestampSigner()
    token = signer.sign(email)

    # Build the verification URL pointing to the frontend application.
    query_string = urlencode({'token': token})
    verify_url = f'{settings.FRONTEND_URL}/auth/verify?{query_string}'

    # Send the email — stubs if Azure not configured locally
    send_magic_link_email(to=email, magic_link_url=verify_url)


def verify_magic_link(token: str) -> User:
    """
    Verify a magic link token and return the authenticated user.

    - Uses TimestampSigner to validate the token.
    - The token expires after 15 minutes.
    - On success, Django session is established by the calling view.

    Args:
        token: The signed token from the query string.


    Returns:
        The authenticated User instance.

    Raises:
        AppError(INVALID_TOKEN, 400): If the token is invalid or expired.
    """
    from django.core.signing import TimestampSigner, SignatureExpired, BadSignature

    signer = TimestampSigner()
    try:
        email = signer.unsign(token, max_age=900)
    except SignatureExpired as e:
        raise AppError(
            code='INVALID_TOKEN',
            message='This link has expired. Please request a new one.',
            status=400,
        ) from e
    except BadSignature as e:
        raise AppError(
            code='INVALID_TOKEN',
            message='This link is invalid. Please request a new one.',
            status=400,
        ) from e

    # Find the user case-insensitively, or create them if they don't exist
    user = User.objects.filter(email__iexact=email).first()
    if not user:
        user = User.objects.create(
            email=email,
            full_name='',
            is_cu_student=_is_cu_student(email),
            role=UserRole.STUDENT,
        )

        logger.info('New user created via magic link verification: User ID %s', user.id)

    # Sync is_staff and is_superuser with role — admin users need is_staff=True and is_superuser=True for Django Admin
    if user.role == UserRole.ADMIN and (not user.is_staff or not user.is_superuser):
        User.objects.filter(pk=user.pk).update(is_staff=True, is_superuser=True)
        user.is_staff = True
        user.is_superuser = True

    logger.info('User logged in via magic link: User ID %s', user.id)
    return user


def update_user_profile(user: User, validated_data: dict) -> User:
    """
    Update mutable profile fields on the user's own account.

    Only updates fields provided in validated_data (PATCH semantics).
    Email and role cannot be changed here.

    Returns the updated user instance.
    """
    for field, value in validated_data.items():
        setattr(user, field, value)
    user.save(update_fields=[*validated_data.keys(), 'updated_at'])

    # Sync changes to linked team profile(s)
    if hasattr(user, 'team_profile'):
        for member in user.team_profile.all():
            team_updates = []
            if 'full_name' in validated_data:
                member.full_name = validated_data['full_name']
                team_updates.append('full_name')
            if 'github_url' in validated_data:
                member.github_url = validated_data['github_url']
                team_updates.append('github_url')
            if 'linkedin_url' in validated_data:
                member.linkedin_url = validated_data['linkedin_url']
                team_updates.append('linkedin_url')
            if team_updates:
                member.save(update_fields=team_updates)

    return user


def change_user_role(target_user: User, new_role: str, changed_by: User) -> User:
    """
    Change a user's role. Admin-only action — enforced by view permissions.

    Syncs is_staff when changing to/from admin role.

    Args:
        target_user: The user whose role is being changed.
        new_role: One of 'student', 'volunteer', 'admin'.
        changed_by: The admin performing the change (for audit logging).

    Returns the updated user instance.
    """
    if new_role not in UserRole.values:
        raise AppError(
            code='VALIDATION_ERROR',
            message='Invalid role.',
            fields={'role': f'Must be one of: {", ".join(UserRole.values)}.'},
            status=400,
        )

    old_role = target_user.role
    target_user.role = new_role

    # Keep is_staff in sync with admin role
    target_user.is_staff = (new_role == UserRole.ADMIN)
    target_user.is_superuser = (new_role == UserRole.ADMIN)

    target_user.save(update_fields=['role', 'is_staff', 'is_superuser', 'updated_at'])

    logger.info(
        'User %s role changed from %s to %s by admin %s',
        target_user.email, old_role, new_role, changed_by.email,
    )
    return target_user


def get_user_list(role: str | None = None, search: str | None = None):
    """
    Return a queryset of all users, optionally filtered.
    Admin-only — permission enforced by view.
    """
    from django.db.models import F, Window
    from django.db.models.functions import Rank
    qs = User.objects.annotate(
        annotated_rank=Window(
            expression=Rank(),
            order_by=F('club_points').desc(nulls_last=True)
        )
    )

    if role:
        if role not in UserRole.values:
            raise AppError(
                code='VALIDATION_ERROR',
                message='Invalid role filter.',
                fields={'role': f'Must be one of: {", ".join(UserRole.values)}.'},
            )
        qs = qs.filter(role=role)

    if search:
        from django.db.models import Q
        qs = qs.filter(
            Q(full_name__icontains=search) | Q(email__icontains=search)
        )

    return qs
