# Generated by Django 6.0.6 on 2026-07-20 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_method', models.CharField(blank=True, choices=[('qr', 'QR Scan'), ('manual', 'Manual')], max_length=10, null=True)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='attendance.attendancerecord')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Check In',
                'verbose_name_plural': 'Daily Check Ins',
                'db_table': 'attendance_dailycheckin',
                'ordering': ['-date', '-checked_in_at'],
                'constraints': [models.UniqueConstraint(fields=('attendance_record', 'date'), name='unique_daily_checkin')],
            },
        ),
    ]
