# Generated by Django 6.0.6 on 2026-06-23 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_teammember',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['display_order'], name='team_teamme_display_2f58ff_idx'), models.Index(fields=['is_active'], name='team_teamme_is_acti_217493_idx')],
            },
        ),
    ]
