# Generated by Django 6.0.6 on 2026-07-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_github_url_teammember_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
    ]
