# Generated by Django 6.0.6 on 2026-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teammember_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
