# Generated by Django 6.0.6 on 2026-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_teammember_twitter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('Leadership', 'Leadership'), ('Technical', 'Technical'), ('Design', 'Design'), ('Media', 'Media'), ('Marketing', 'Marketing'), ('Volunteers', 'Volunteers'), ('Faculty', 'Faculty')], default='Volunteers', max_length=50),
        ),
    ]
