# Generated by Django 6.0.6 on 2026-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='show_on_homepage',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
