# Generated by Django 6.0.6 on 2026-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_degree_type_user_graduation_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
