# Generated by Django 6.0.6 on 2026-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_branch_remove_user_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_uid',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
