# Generated by Django 6.0.6 on 2026-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='previous_events_count',
            field=models.IntegerField(default=0, help_text='Number of events hosted before this platform was built.'),
        ),
    ]
